# Generated by Django 2.2 on 2022-04-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryId',
            new_name='category',
        ),
    ]
