# Generated by Django 2.2 on 2022-05-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=400)),
                ('shipping_type', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=40)),
                ('e_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shipping')),
            ],
        ),
    ]
