# Generated by Django 2.2 on 2022-05-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220503_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shipping',
        ),
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
            preserve_default=False,
        ),
    ]
