# Generated by Django 2.2 on 2022-05-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220503_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='fullName',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
